### 获取用户信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service":"cn.theodore.tedrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

###
POST http://localhost:8081/
Content-Type: application/json

{
  "service":"cn.theodore.tedrpc.demo.api.UserService",
  "methodSign":"findById@2_int_java.lang.String",
  "args":[100,"cc"]
}

###
POST http://localhost:8081/
Content-Type: application/json

{
  "service":"cn.theodore.tedrpc.demo.api.UserService",
  "methodSign":"find@1_int",
  "args":[2000]
}

### 获取用户信息 均衡负载
GET http://localhost:8088/?id=101
Content-Type: application/json