server:
  port: 8081

tedrpc:
  zk:
    server: localhost:2181
    root: tedprc
  app:
    id: app1
    namespace: public
    env: dev
  providers:
    metas:
      dc: bj
      gray: false
      unity: B001
      tc: 300

logging:
  level:
    root: error
    cn.theodore.tedrpc: info