server:
  port: 8081

tedrpc:
  zk:
      server: localhost:2181
      root: tedrpc

app:
  id: app1
  namespace: public
  env: dev

# 注册中心
tedregistry:
  servers: http://localhost:8484

logging:
  level:
    root: error
    cn.theodore.tedrpc: info